apiVersion: apps/v1
kind: Deployment
metadata:
  name: actiondemo01-deployment
spec:
  selector:
    matchLabels:
      app: actiondemo01-pod
  template:
    metadata:
      labels:
        app: actiondemo01-pod
    spec:
      containers:
      - name: actiondemo01-container
        image: acrskhor.azurecr.io/actiondemo01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000