name: Docker Image Helm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  HELM_EXPERIMENTAL_OCI: 1


jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag acrskhor.azurecr.io/actiondemo01:latest
   
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: acrskhor # ${{ secrets.ACR_NAME }}
        # Container registry password
        password: DWtSUEvTKHTnMDEe6ClAVUTOoGrCR+ve
        # Container registry server url
        login-server: acrskhor.azurecr.io
    - name: Push the Docker image
      run: docker push acrskhor.azurecr.io/actiondemo01:latest
    
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1
        
    - name: Login to ACR using HELM
      run: |
        echo $ | helm registry login acrskhor.azurecr.io --username acrskhor --password DWtSUEvTKHTnMDEe6ClAVUTOoGrCR+ve
        
    - name: Package the helm chart
      run: helm package ./helm/actiondemo01-api
      
    - name: save helm chart to local registry
      run: |
       helm chart save ./actiondemo01-api-0.1.0.tgz acrskhor.azurecr.io/charts-actiondemo01-api:latest
       
    - name: Helm chart Push
      run: helm chart push acrskhor.azurecr.io/charts-actiondemo01-api:latest

 
 
 
  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image # Will wait for the execution of the previous job
    
    steps:
      - uses: actions/checkout@v2
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1.1
        with:
          # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
          creds: ${{ secrets.AKS_CREDS }}
          # Resource Group Name
          resource-group: kub-rg
          # AKS Cluster Name
          cluster-name: aks_khor2
        
      - name: Helm tool installer
        uses: Azure/setup-helm@v1
        with:
          # Version of helm
          version: 3.3.1
          
      - name: Login to ACR using HELM
        run: |
          echo $ | helm registry login acrskhor.azurecr.io --username acrskhor --password DWtSUEvTKHTnMDEe6ClAVUTOoGrCR+ve
          
      - name : Set Helm Env Var
        run : export HELM_EXPERIMENTAL_OCI=1  
        
      - name: Helm Chart Pull
        run: helm chart pull acrskhor.azurecr.io/charts-actiondemo01-api:latest
    
      - name: Helm Chart Move
        run: helm chart export acrskhor.azurecr.io/charts-actiondemo01-api:latest --destination ./install
        
      - name: Helm Chart Install
        run: helm upgrade --namespace ns-dev --install --set image.tag=latest actiondemo01-api ./install/actiondemo01-api # release name chart name
     
      
      
      
      
      
      
      

      





#     - name: Apply AKS Deployment
#       run: kubectl apply -f deployment.yaml
      
#     - name: Apply AKS Deployment
#       run: kubectl apply -f service.yaml
    
    
    
 
 
  
    
