name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag acrskhor.azurecr.io/actiondemo01:latest
   
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: acrskhor 
        # Container registry password
        password: DWtSUEvTKHTnMDEe6ClAVUTOoGrCR+ve
        # Container registry server url
        login-server: acrskhor.azurecr.io
    - name: Push the Docker image
      run: docker push acrskhor.azurecr.io/actiondemo01:latest

  deploy:
      runs-on: ubuntu-latest
      needs: build # Will wait for the execution of the previous job
      
      steps:
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1.1
        with:
          # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
          creds: ${{ secrets.AKS_CREDS }}
          # Resource Group Name
          resource-group: kub-rg
          # AKS Cluster Name
          cluster-name: aks_khor2
