name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag acrskhor.azurecr.io/actiondemo01:latest
   
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: acrskhor 
        # Container registry password
        password: DWtSUEvTKHTnMDEe6ClAVUTOoGrCR+ve
        # Container registry server url
        login-server: acrskhor.azurecr.io
    - name: Push the Docker image
      run: docker push acrskhor.azurecr.io/actiondemo01:latest
